## This is the system configuration file for the NVMe-based GPU storage system.
## It defines the GPU and NVMe device settings, including mount paths, PCI addresses, queue depths, and CUDA device assignments.   
## The [GPU0] section specifies the settings for the GPU device, including the mount path for the NVMe layer and the CUDA device ID.
## The [NVMe1] and [NVMe2] sections specify the settings for two NVMe devices, including their mount paths, PCI addresses, namespace IDs, queue depths, number of queues, CUDA device assignments, and maximum I/O sizes.
## The [NVMe1] and [NVMe2] following [GPU] means that these NVMe devices are associated with the GPU specified in the [GPU0] section.
## system may have more GPU and NVMe sections if there are multiple GPUs and NVMe devices in the system.
<GRPC>
endpoint = "127.0.0.1:50051"
max_queues_per_process = 64

<GPU0>
mount_path = "/mnt/nvme_layer"
cudaDevice = 1

<NVMe1>
mount_path = "nvme1"
pci_addr = "0000:41:00.0"
ns_id = 1
queueDepth = 1024
numQueues = 128
cudaDevice = 1
maxIOsize = 1024

<NVMe2>
mount_path = "nvme2"
pci_addr = "0000:42:00.0"
ns_id = 1
queueDepth = 1024
numQueues = 128
cudaDevice = 1
maxIOsize = 1024